"""Declarative metric whitelists for the runs dashboard extractor.

Add a field name here when extract should keep it in site/data.
Add a CHART_SPECS entry in static/assets/charts.js to plot it.
Topology-derived scalars are computed in topology_metrics.py (not listed here).
"""

from __future__ import annotations

# Keys kept from each history_compact point (ova_results rows).
HISTORY_KEYS: tuple[str, ...] = (
    "generation",
    "best_fitness",
    "best_bal_acc",
    "best_acc",
    "best_f1",
    "best_mcc",
    "best_precision",
    "best_recall",
    "best_roc_auc",
    "best_pr_auc",
    "best_sweep_bal_acc",
    "best_informedness",
    "best_log_loss",
    "best_nodes",
    "best_edges",
    "best_edges_executed",
    "mean_acc",
    "population_size",
    "eval_batch_size",
    "eval_edges_enabled",
    "eval_edges_executed",
    "eval_genomes_per_sec",
    "wall_gen_sec",
    "wall_elapsed_sec",
    "timing_eval_sec",
    "timing_evolve_sec",
    "timing_generation_sec",
    "timing_metrics_sec",
    "timing_save_sec",
    "timing_dashboard_sec",
    "timing_periodic_gd_sec",
    "timing_elite_refinement_sec",
    "forward_hash_cache_bytes",
    "forward_hash_cache_entries",
    "forward_hash_cache_mode",
    "forward_hash_cache_hit_rate",
    "forward_hash_cache_planned_waves",
    "periodic_gd_applied",
    "elite_refinement_applied",
    "elite_refinement_count",
)

# Peak / identity fields kept on each ova_results row (config_signature stripped).
RESULT_ROW_KEYS: tuple[str, ...] = (
    "phase",
    "stage",
    "class_id",
    "class_name",
    "config_name",
    "run_id",
    "run_path",
    "num_generations",
    "stopped_reason",
    "stagnation_patience",
    "elapsed_sec",
    "timestamp",
    "best_fitness",
    "best_bal_acc",
    "best_acc",
    "best_f1",
    "best_precision",
    "best_recall",
    "best_mcc",
    "best_roc_auc",
    "best_pr_auc",
    "best_sweep_bal_acc",
    "best_informedness",
    "best_log_loss",
    "final_nodes",
    "final_edges",
    "final_edges_executed",
    "history_compact",
    "error",
)

# Keys kept from run_archive epochs[*].summary
EPOCH_SUMMARY_KEYS: tuple[str, ...] = (
    "generation",
    "best_fitness",
    "mean_fitness",
    "best_idx",
    "best_nodes",
    "best_edges",
    "best_edges_executed",
    "best_acc",
    "best_bal_acc",
    "best_f1",
    "best_mcc",
    "best_precision",
    "best_recall",
    "best_roc_auc",
    "best_pr_auc",
    "best_sweep_bal_acc",
    "sweep_bal_acc",
    "sweep_mcc",
    "sweep_f1",
    "sweep_threshold",
    "sweep_mcc_threshold",
    "sweep_bal_threshold",
    "informedness",
    "log_loss",
    "ap",
    "tp",
    "tn",
    "fp",
    "fn",
    "population_size",
    "eval_sample_count",
    "eval_batch_size",
    "eval_edges_enabled",
    "eval_edges_executed",
    "timing_eval_sec",
    "timing_generation_sec",
    "timing_metrics_sec",
    "timing_evolve_sec",
    "timing_periodic_gd_sec",
    "timing_elite_refinement_sec",
    "eval_genomes_per_sec",
    "fitness_metric",
    "periodic_gd_applied",
    "elite_refinement_applied",
    "elite_refinement_count",
    "forward_hash_cache_bytes",
    "forward_hash_cache_entries",
    "forward_hash_cache_hit_rate",
)

# Lite meta from run_archive.meta (no nested study_signature blobs).
META_KEYS: tuple[str, ...] = (
    "activation",
    "output_readout",
    "edge_weights",
    "population_size",
    "fitness_metric",
    "periodic_gd_enabled",
    "positive_class",
    "num_generations_planned",
    "allowed_channels",
    "allow_variable_channels",
    "experiment_name",
    "run_id",
    "input_channels",
    "input_image_size",
    "output_image_size",
    "seed",
    "stagnation_patience",
    "archive_weights_policy",
)

CONE_KEYS: tuple[str, ...] = (
    "generation",
    "breeding_cone_nodes",
    "breeding_cone_unused",
    "breeding_cone_orphaned",
    "breeding_cone_fill_frac",
    "breeding_cone_serve_hits",
    "breeding_cone_serve_shortfall",
    "breeding_cone_roots",
    "breeding_cone_elites",
    "breeding_cone_hashes_ready",
    "breeding_cone_hashes_pending",
    "breeding_cone_pruned_nodes",
    "breeding_cone_rss_bytes",
    "breeding_cone_ram_cap_bytes",
    "breeding_cone_effective_current",
    "breeding_cone_effective_next",
    "breeding_cone_depth_max",
    "breeding_cone_max_depth",
    "breeding_cone_ready_total",
    "breeding_cone_multiprocess",
    "breeding_cone_processes",
    "timing_cone_expand_sec",
    "timing_cone_serve_sec",
    "timing_cone_orphan_sec",
    "timing_cone_gc_sec",
)

CACHE_KEYS: tuple[str, ...] = (
    "generation",
    "hit_rate",
    "hits",
    "misses",
    "evictions",
    "bytes_used",
    "resident_bytes",
    "gpu_bytes",
    "cpu_bytes",
    "pending_bytes",
    "peak_bytes",
    "max_bytes",
    "entries",
    "dup_bytes_saved",
    "gpu_spills",
    "gpu_spill_bytes",
    "overlay_nodes",
    "overlay_shared",
    "overlay_resident",
    "resident_vertex_count",
    "resident_vertex_bytes_per_sample_max",
    "resident_vertex_bytes_per_sample_sum",
    "forward_per_sample_bytes_estimated_max",
    "bytes_per_entry",
    "bytes_per_breeder",
    "breeding_pool_size",
    "population_size",
)

HOLDOUT_RESULT_KEYS: tuple[str, ...] = (
    "phase",
    "class_id",
    "class_name",
    "config_name",
    "run_id",
    "champion_generation",
    "champion_index",
    "val_best_fitness",
    "val_best_bal_acc",
    "val_best_acc",
    "val_best_f1",
    "val_best_mcc",
    "val_best_roc_auc",
    "val_best_pr_auc",
    "test_balanced_accuracy",
    "test_accuracy",
    "test_f1",
    "test_mcc",
    "test_roc_auc",
    "test_pr_auc",
    "gap_bal_acc",
    "gap_acc",
    "gap_f1",
    "gap_mcc",
    "archive_peak_fitness",
    "champion_archive_fitness",
    "champion_fallback_fitness_gap",
    "error",
)

# Max points kept for study-level cone/cache histories (thinning).
HISTORY_MAX_POINTS = 2000
